language: node_js
node_js: 10
before_script:
  - npm run build
script:
  - echo true
before_deploy:
  - PUBLIC_URL=https://nicolas-van.github.io/jsgame/ npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  local-dir: dist
  on:
    branch: master
